# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches:
      - main
      - master
      - "r-*"
  pull_request:
    branches:
      - main
      - master
      - "r-*"
  schedule:
    - cron:  '10 0 * * *'

name: rcc

jobs:
  # Windows checks are run in parallel and independently,
  # because they alone can take as long as the smoke and full tests combined.
  R-CMD-check-windows:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.desc }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      matrix:
        config:
          # Use 3.6 to trigger usage of RTools35
          - {os: windows-latest, r: '3.6'}

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/custom/before-install

      - uses: ./.github/workflows/install
        with:
          r-version: ${{ matrix.config.r }}
          cache-version: rcc-main-1
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/custom/after-install

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - uses: ./.github/workflows/check
        with:
          results: ${{ runner.os }}-r${{ matrix.config.r }}
